[package]
name = "zram-generator"
version = "0.2.0-beta.1"
authors = ["Zbigniew Jędrzejewski-Szmek <zbyszek@in.waw.pl>"]
license = "MIT"
description = "Systemd unit generator for zram swap devices"
homepage = "https://github.com/systemd/zram-generator"
edition = "2018"

[dependencies]
anyhow = "1.0.12"
clap = { version = "2.33", default-features = false }
liboverdrop = "0.0.2"
rust-ini = ">=0.13, <0.16"

[dev-dependencies]
tempfile = "3"
fs_extra = "1.1"

[profile.release]
lto = true
